// src/app/create-task-popup/create-task-popup.component.ts
import { Component, Input, Output, EventEmitter } from '@angular/core';
import { apiService } from '../../shared/api/swagger/swagger';

@Component({
  selector: 'app-create-task-popup',
  templateUrl: './create-task-popup.component.html',
  styleUrls: ['./create-task-popup.component.scss']
})
export class CreateTaskPopupComponent {
  @Input() isOpen: boolean = false;
  @Input() statusId: any;
  @Input() tasks: any[] = [];

  @Output() isOpenChange = new EventEmitter<boolean>();
  @Output() tasksChange = new EventEmitter<any[]>();

  public task = {
    status_id: '',
    title: '',
    description: ''
  };
  closePopup() {
    this.isOpenChange.emit(false);
  }

  saveTask() {
    apiService.tasks.Create({
      status_id: +this.task.status_id,
      title: this.task.title,
      description: this.task.description
    }).then(() => {
      apiService.tasks.Get().then((res) => {
        this.tasksChange.emit(res.data);
      }).then(() => {
        this.closePopup();
      });
    });
  }



  updateTask(value: any) {
    this.task = { ...this.task, ...value };
  }

  titleElement() {
    return `создать задачу`;
  }

  contentElement() {
    return `
      <h1>eooeoeoeoeoeoe</h1>
    `;
  }

  actionsElement() {
    return `
      <app-button (click)="closePopup()" type="text">ОТМЕНА</app-button>
      <app-button (click)="saveTask()">СОХРАНИТЬ</app-button>
    `;
  }
}

<app-popup [isOpen]="isOpen" [title]="titleElement()">
    <div [innerHtml]="contentElement()" content></div>
    <div class="popup_actions" actions>
        <app-button (click)="closePopup()" text="OTMEНА"></app-button>
        <app-button (click)="saveTask()" text="СОХРАНИТЬ"></app-button>
    </div>
</app-popup>

// src/app/components/Task/CreateTaskPopup/index.jsx
import React, { useState } from "react";

import { apiService } from "../../../shared/api/swagger/swagger";

import { Popup, Button, ContentPopup } from '../..';

const CreateTaskPopup = ({ isDialog, show, updateTasks }) => {
  const closePopup = () => {
    show(false);
  }

  const [task, setTask] = useState({
    status_id: isDialog,
    title: "",
    description: "",
  })

  const updateTask = (task) => {
    setTask(task);
  }

  const saveTask = () => {
    apiService.tasks.Create(task).then(() => {
      apiService.tasks
        .Get()
        .then((res) => {
          updateTasks(res.data);
        })
        .then(() => {
          closePopup();
        });
    });
  };

  const titleElement = () => {
    return (
      <>создать задачу</>
    )
  }

  const contentElement = () => {
    return (
      <>
        <ContentPopup newTask={task} updateTask={(value) => updateTask({...task, ...value})} />
      </>
    )
  }

  const actionsElement = () => {
    return (
      <>
        <Button onClick={closePopup} type={'text'}>ОТМЕНА</Button>
        <Button onClick={saveTask}>СОХРАНИТЬ</Button>
      </>
    )
  }

  return (
    <Popup
      isOpen={isDialog}
      title={titleElement()}
      content={contentElement()}
      actions={actionsElement()}
    />
  )
}

export { CreateTaskPopup }
