// src/app/components/Task/CreateTaskPopup/index.jsx
import React, { useState } from "react";

import { apiService } from "../../../shared/api/swagger/swagger";

import { Popup, Button, ContentPopup } from '../..';

const CreateTaskPopup = ({ isDialog, show, updateTasks }) => {
  const closePopup = () => {
    show(false);
  }

  const [task, setTask] = useState({
    status_id: isDialog,
    title: "",
    description: "",
  })

  const updateTask = (task) => {
    setTask(task);
  }

  const saveTask = () => {
    apiService.tasks.Create(task).then(() => {
      apiService.tasks
        .Get()
        .then((res) => {
          updateTasks(res.data);
        })
        .then(() => {
          closePopup();
        });
    });
  };

  const titleElement = () => {
    return (
      <>создать задачу</>
    )
  }

  const contentElement = () => {
    return (
      <>
        <ContentPopup newTask={task} updateTask={(value) => updateTask({...task, ...value})} />
      </>
    )
  }

  const actionsElement = () => {
    return (
      <>
        <Button onClick={closePopup} type={'text'}>ОТМЕНА</Button>
        <Button onClick={saveTask}>СОХРАНИТЬ</Button>
      </>
    )
  }

  return (
    <Popup
      isOpen={isDialog}
      title={titleElement()}
      content={contentElement()}
      actions={actionsElement()}
    />
  )
}

export { CreateTaskPopup }

// src/app/components/create-task-popup/create-task-popup.component.ts
import { Component, Input, Output, EventEmitter, DoCheck } from '@angular/core';
import { apiService } from '../../../shared/api/swagger/swagger';

@Component({
  selector: 'app-create-task-popup',
  templateUrl: './create-task-popup.component.html',
  styleUrls: ['./create-task-popup.component.scss']
})
export class CreateTaskPopupComponent implements DoCheck {
  @Input() isOpen: boolean = false;
  @Input() statusId: any;
  @Input() tasks: any[] = [];

  @Output() isOpenChange = new EventEmitter<boolean>();
  @Output() tasksChange = new EventEmitter<any[]>();

  public task = {
    status_id: '',
    title: '',
    description: ''
  };

  closePopup() {
    this.isOpenChange.emit(false);
  }

  ngDoCheck(): void {
    if (this.statusId && !this.task.status_id) {
      this.task = {
        status_id: this.statusId,
        title: '',
        description: ''
      }
    }
  }


  saveTask() {
    apiService.tasks.Create({
      status_id: +this.task.status_id,
      title: this.task.title,
      description: this.task.description
    }).then(() => {
      apiService.tasks.Get().then((res) => {
        this.tasksChange.emit(res.data);
      }).then(() => {
        this.closePopup();
      });
    });
  }



  updateTask(updatedTask: any) {
    this.task = updatedTask; // Update the task object with the updated task
  }

  titleElement() {
    return `создать задачу`;
  }
}

<app-popup [isOpen]="isOpen" [title]="titleElement()">
    <div class="popup_content" content>
        <app-content-popup [(task)]="task" (taskChange)="updateTask($event)"></app-content-popup>
    </div>
    <div class="popup_actions" actions>
        <app-button (click)="closePopup()" text="OTMEНА"></app-button>
        <app-button (click)="saveTask()" text="СОХРАНИТЬ"></app-button>
    </div>
</app-popup>
