// src/app/components/content-popup/content-popup.component.ts
import { Component, Input, Output, EventEmitter} from '@angular/core';

@Component({
  selector: 'app-content-popup',
  templateUrl: './content-popup.component.html',
  styleUrls: ['./content-popup.component.scss']
})
export class ContentPopupComponent {
  @Input() task: any;
  @Output() taskChange = new EventEmitter<any>();

  updateTask() {
    this.taskChange.emit(this.task);
  }

  onValueChange(event: any){
    this.task.status_id = +event;
    this.taskChange.emit(this.task);
  }

  onTitleChange(event: any) {
    this.task.title = event;
    this.taskChange.emit(this.task);
  }

  onDescriptionChange(event: any) {
    this.task.description = event;
    this.taskChange.emit(this.task);
  }

  statuses: any[] = [
    {
      id: 1,
      name: "сделать",
    },
    {
      id: 2,
      name: "в процессе",
    },
    {
      id: 3,
      name: "закончено",
    },
  ];


}

<div class="content-task">
    <app-combobox [(value)]="task.status_id" [list]="statuses" (valueChange)="onValueChange($event)"></app-combobox>
    <app-text-input [(value)]="task.title" [type]="'text'" [placeholder]="'название'" (valueChange)="onTitleChange($event)"></app-text-input>
    <app-text-area [(value)]="task.description" placeholder="описание" (valueChange)="onDescriptionChange($event)"></app-text-area>
</div>

// src/app/components/Task/ContentPopup/index.jsx
import React from "react";

import { Combobox, TextInput, TextArea } from '../..';

import style from './style.module.scss';

const ContentPopup = ({ newTask, updateTask }) => {
  const statuses =  [
        {
          id: 1,
          name: "сделать",
        },
        {
          id: 2,
          name: "в процессе",
        },
        {
          id: 3,
          name: "закончено",
        },
  ]

  const updateValue = (event, prop) => {
    updateTask({ [prop]: event.target.value})
  }

  return (
    <>
      {newTask &&
        <div className={style['content-task']}>
          <Combobox
            value={newTask.status_id}
            onChange={(e) => updateValue(e, 'status_id')}
            list={statuses}
          />
          <TextInput
            value={newTask.title}
            onChange={(e) => updateValue(e, 'title')}
          />
          <TextArea
            value={newTask.description}
            onChange={(e) => updateValue(e, 'description')}
          />
        </div>
      }
    </>
  )
}

export { ContentPopup }
