// src/app/components/edit-task-popup/edit-task-popup.component.ts
import { Component, Input, Output, EventEmitter, DoCheck } from '@angular/core';
import { apiService } from '../../../shared/api/swagger/swagger';


@Component({
  selector: 'app-edit-task-popup',
  templateUrl: './edit-task-popup.component.html',
  styleUrls: ['./edit-task-popup.component.scss']
})
export class EditTaskPopupComponent implements DoCheck {
  @Input() isOpen: boolean = false;
  @Input() taskId: any;
  @Input() tasks: any[] = [];
  @Input() user: any;

  @Output() isOpenChange = new EventEmitter<boolean>();
  @Output() tasksChange = new EventEmitter<any[]>();

  public task: any = {
    status_id: 0,
    title: '',
    description: ''
  };

  closePopup() {
    this.isOpenChange.emit(false);
  }

  ngDoCheck(): void {
    if (this.taskId && !this.task.status_id) {
      apiService.tasks.GetById(this.taskId).then(res => {
        this.task = res.data;
      });
    }
  }


  saveTask() {
    apiService.tasks
            .Update(this.task.id, {
                status_id: this.task.status_id,
                description: this.task.description,
                title: this.task.title,
            })
            .then(() => {
                apiService.tasks
                    .Get()
                    .then((res) => {
                      this.tasksChange.emit(res.data);
                    })
                    .then(() => {
                      this.closePopup();
                    });
            });
  }



  updateTask(updatedTask: any) {
    this.task = updatedTask; // Update the task object with the updated task
  }

  titleElement() {
    return `редактировать задачу`;
  }
}


<app-popup [isOpen]="isOpen" [title]="titleElement()">
    <div class="popup_content" content>
        <app-content-popup [(task)]="task" (taskChange)="updateTask($event)"></app-content-popup>
    </div>
    <div class="popup_actions" actions>
        <app-button (click)="closePopup()" text="OTMEНА"></app-button>
        <app-button *ngIf="task && task.author_id === user" (click)="saveTask()" text="СОХРАНИТЬ"></app-button>
    </div>
</app-popup>

// src/app/components/Task/EditTaskPopup/index.jsx
import React, { useState, useEffect } from "react";

import { apiService } from "../../../shared/api/swagger/swagger";

import { Popup, Button, ContentPopup } from '../..';

const EditTaskPopup = ({ isDialog, show, user, updateTasks }) => {
  const [task, setTask] = useState({
    status_id: -1,
    title: "",
    description: "",
  });

  const closePopup = () => {
    show(false);
  };

  const updateTask = (task) => {
    setTask(task);
  };

  const saveTask = () => {
    apiService.tasks
      .Update(task.id, {
        status_id: task.status_id,
        description: task.description,
        title: task.title,
      })
      .then(() => {
        apiService.tasks
          .Get()
          .then((res) => {
            updateTasks(res.data);
          })
          .then(() => {
            closePopup();
          });
      });
  };

  const titleElement = () => {
    return (
      <>редактировать задачу</>
    )
  };

  const contentElement = () => {
    return (
      <>
        <div>
          <ContentPopup newTask={task} updateTask={(value) => updateTask({...task, ...value})} />
        </div>
      </>
    )
  };

  const actionsElement = () => {
    return (
      <>
        <Button onClick={closePopup} type={'text'}>ОТМЕНА</Button>
        {task && task.author_id === user &&
          <Button onClick={saveTaskgit }>СОХРАНИТЬ</Button>
        }
      </>
    )
  };

  useEffect(() => {
    apiService.tasks.GetById(isDialog).then((res) => {
      updateTask(res.data);
    });
  }, []);

  return (
    <Popup
      isOpen={isDialog}
      title={titleElement()}
      content={contentElement()}
      actions={actionsElement()}
    />
  )
}

export { EditTaskPopup }
